config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get  'settings', to: 'users#edit'
  get  'orders', to: 'orders#index'

#   get   'settings/addresses', to: 'addresses#edit'
#   post  'settings/addresses', to: 'addresses#create'
#   patch 'settings/addresses', to: 'addresses#update'
  resources settings do
    resources addresses, only: %i[create update]
  end
      

  resources :checkout
  resources :order_items, only: %i[create update destroy]

  resource :cart, only: %i[show update]

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :confirmable, :omniauthable, omniauth_providers: %i[facebook]

  belongs_to :shipping_address, class_name: 'Address', optional: true, autosave: true
  belongs_to :billing_address, class_name: 'Address', optional: true, autosave: true

  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :email,
            uniqueness: true,
            presence: true,
            format: { with: /@/, message: 'invalid format' }
  validates :encrypted_password, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def edit; end

  def update_password
    if @user.update_with_password(user_params_password)
      redirect_to root_path
      flash[:success] = t('devise.pass_changed')
    else
      flash[:warning] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update_email
    @user.skip_reconfirmation!
    if @user.update_without_password(user_params_email)
      flash[:success] = t('devise.email_changed')
    else
      flash[:warning] = @user.errors.full_messages.to_sentence
    end
    redirect_to settings_path
  end

  private

  def user_params_password
    params.require(:user).permit(:password, :current_password, :password_confirmation)
  end

  def user_params_email
    params.require(:user).permit(:email)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/_edit_email.html.haml
= form_for(@user, url: { action: "update_email" }, html: {class: 'general-form-md email' }) do |f|
  .form-group.mb-30
    = f.label :email, class: "control-label input-label"
    = f.email_field :email, class: "form-control"
  .form-group.mb-30
    = f.submit t('addresses.save'), class: 'btn btn-default mb-10', id: 'email_btn'

app/views/users/_edit_password.html.haml
= form_for(@user, url: {action: "update_password"}, html: { class: 'general-form-md divider-lg-bottom pb-25' } )do |f|
  .form-group.mb-30
    = f.label :current_password, class: "control-label input-label"
    = f.password_field :current_password, class: "form-control"
  .form-group.mb-30
    = f.label :password, class: "control-label input-label"
    = f.password_field :password, class: "form-control"
  .form-group.mb-30
    = f.label :password_confirmation, class: "control-label input-label"
    = f.password_field :password_confirmation, class: "form-control"
  .general-text-align
    = f.submit t('addresses.save'), class: 'btn btn-default mb-10', id: 'pass_btn'

app/views/users/_remove_account.html.haml
.general-settings-btn
  = button_to t('addresses.please_remove_account'), registration_path(current_user), id: 'destroy_confirmation_button', disabled: true, class: 'button btn-default mb-20', method: :delete
.form-group.checkbox.general-settings-checkbox
  %label.checkbox-label
    = check_box_tag 'destroy_confirmation', true, false, id: 'destroy_confirmation', class: 'checkbox-input', hidden: true
    %span.checkbox-icon
      %i 
    %span.checkbox-text 
      =t('addresses.i_understand')

app/views/users/edit.html.haml
%main.container
  %h1.general-title-margint=t('addresses.settings')
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item.active{role: "presentation"}
      %a.tab-link{href: "/settings/addresses"}=t('addresses.address')
    %li.tab-item{role: "presentation"}
      %a.tab-link{href: "/settings"}=t('addresses.privacy')
  .tab-content
    #privacy.tab-pane.fade.in.active.general-main-wrap{role: "tabpanel"}
      .row.mb-60
        .col-sm-5
          %p.in-gold-500.font-18.mb-25=t('addresses.email')
          = render 'edit_email'
        .col-sm-5.col-sm-offset-1
          %p.in-gold-500.font-18.mb-25=t('addresses.password')
          = render 'edit_password'
        .col-sm-12
          %p.in-gold-500.font-18.mb-25=t('addresses.remove_account')
          = render 'remove_account'