config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get  'settings', to: 'users#edit'
  get  'orders', to: 'orders#index'

#   get   'settings/addresses', to: 'addresses#edit'
#   post  'settings/addresses', to: 'addresses#create'
#   patch 'settings/addresses', to: 'addresses#update'
  resources settings do
    resources addresses, only: %i[create update]
  end
      

  resources :checkout
  resources :order_items, only: %i[create update destroy]

  resource :cart, only: %i[show update]

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller
class HomeController < ApplicationController
  def index
    @books = Book.all
    @newest = NewestBooksQuery.call
    @top_books = TopBooksQuery.call
  end
end

app/views/home/_best_selers.html.haml
.col-sm-6.col-md-3
  .general-thumb-wrap
    .thumbnail.general-thumbnail
      = image_tag book.covers.first.variant(resize: "180x180").processed, class: "img-shadow general-thumbnail-img"
      .thumb-hover
        .general-thumb-link-wrap
          = link_to book_path(book), class: "thumb-hover-link" do
            %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
          = link_to order_items_path(order_item: { book_id: book.id, quantity: 1 }), method: :post, class: "thumb-hover-link" do
            %i.fa.fa-shopping-cart.thumb-icon
  .mb-35
    .clearfix
      %p.pull-right.font-16.in-gold-500= price_euro(book.price)
      %p.title.mr-55= book.title
    %span.divider-sm
    %p.lead.small 
      - book.authors.each do |author|
        = author.name

app/views/home/_top.html.haml
.row
  .col-sm-5
    .general-img-wrap
      %img.img-shadow.general-thumbnail-img{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
  .col-sm-7
    .mb-60
      %h1= @book.title
      %p.lead= @book.description
      %p.lead.small
        - @book.authors.each do |author|
          = author.name
      .general-align
        %button.btn.btn-primary Buy Now

app/views/home/_top_books.html.haml
- @newest.each_with_index do |book, index|
  .carousel-item{class: "#{index == 0 ? 'active' : ''}"}
    .row#ddfde
      .col-sm-5
        .general-img-wrap
          = image_tag book.covers.first.variant(resize: "250x250").processed, class: "img-shadow general-thumbnail-img"
      .col-sm-7
        .mb-60
          %h1= book.title
          %p.lead= book.description
          %p.lead.small
            - book.authors.each do |author|
              = author.name
          .general-align
            = link_to order_items_path(order_item: { book_id: book.id, quantity: 1 }), method: :post do
              %button.btn.btn-primary=t('home_page.buy_now')

app/views/home/index.html.haml
%main.container
  #slider.carousel.slide{'data-ride': "carousel"}
    %ol.carousel-indicators
      %li{"data-slide-to" => "0", "data-target" => "#slider"}
      %li{"data-slide-to" => "1", "data-target" => "#slider"}
      %li{"data-slide-to" => "2", "data-target" => "#slider"}
    .carousel-inner{role: "listbox"}
      = render partial: 'home/top_books'
    %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
      %span.icon-prev{'aria-hidden': "true"}
      %span.sr-only=t('home_page.previous')
    %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
      %span.icon-next{'aria-hidden': "true"}
      %span.sr-only=t('home_page.next')
.container
  .jumbotron.text-center.mb-0
    %h2.h1=t('home_page.welcome')
    .mb-res-50
      %p=t('home_page.under_welcome')
    %a{href: "/books", class: "button btn btn-default"}=t('home_page.get_started')
  .mb-35
    %h3=t('home_page.best_sellers')
    .row
      = render partial: 'home/best_selers', collection: @top_books, as: :book