config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get  'settings', to: 'users#edit'
  get  'orders', to: 'orders#index'

#   get   'settings/addresses', to: 'addresses#edit'
#   post  'settings/addresses', to: 'addresses#create'
#   patch 'settings/addresses', to: 'addresses#update'
  resources settings do
    resources addresses, only: %i[create update]
  end
      

  resources :checkout
  resources :order_items, only: %i[create update destroy]

  resource :cart, only: %i[show update]

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
end

app/views/navbars/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            %a.nav-link{href: "/"}=t('header_footer.home')
          %li
            %a.nav-link{href: "/books"}=t('header_footer.shop')
          - if user_signed_in?
            %li
              %a.nav-link{href: "/orders"}=t('header_footer.orders')
            %li
              %a.nav-link{href: "/settings"}=t('header_footer.settings')
      .col-sm-3
        %p.general-nav-mail=t('header_footer.email')
        %p.general-nav-number=t('header_footer.phone_num')
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "https://www.facebook.com/"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "https://www.twitter.com/"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "https://www.plus.google.com/"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "https://www.instagram.com/"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/navbars/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t('header_footer.bookstore'), books_path, class: "navbar-brand"
    %a.shop-link.pull-right.hidden-xs{href: "/cart"}
      %span.shop-icon
        %span.shop-quantity= current_order&.order_items&.count
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            %a{href: "/"}=t('header_footer.home')
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}=t('header_footer.shop')
            %ul.dropdown-menu
              %li
                %a{href: "/books"}=t('header_footer.all')
              %li
                %a.collapse-link{href: "/books?category_id=1"}=t('header_footer.mobile')
              %li
                %a.collapse-link{href: "/books?category_id=2"}=t('header_footer.photo')
              %li
                %a.collapse-link{href: "/books?category_id=3"}=t('header_footer.web')
          - unless user_signed_in?
            %li
              %a{href: "/users/sign_in"}=t('header_footer.log_in')
            %li
              %a{href: "/users/sign_up"}=t('header_footer.sign_up')
          - if user_signed_in?
            %li.dropdown#my_account
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}=t('header_footer.my_account')
              %ul.dropdown-menu
                %li
                  %a.collapse-link.orders{href: "/orders"}=t('header_footer.orders')
                %li
                  %a.collapse-link{href: "/settings"}=t('header_footer.settings')
                %li.divider{role: "separator"}
                %li
                  = link_to t('header_footer.log_out'), destroy_user_session_path, method: :delete