config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get  'settings', to: 'users#edit'
  get  'orders', to: 'orders#index'

#   get   'settings/addresses', to: 'addresses#edit'
#   post  'settings/addresses', to: 'addresses#create'
#   patch 'settings/addresses', to: 'addresses#update'
  resources settings do
    resources addresses, only: %i[create update]
  end
      

  resources :checkout
  resources :order_items, only: %i[create update destroy]

  resource :cart, only: %i[show update]

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show] do
    resources :reviews, only: :create
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items.by_created
    @discount = current_order.discount
    @subtotal_price_sum = current_order.subtotal_price
    @item_total_price = current_order.price_with_disc
  end

  def update
    user_coupon = Coupon.find_by(active: true, code: params[:code])
    if user_coupon
      user_coupon.update(order: current_order)
    else
      current_order.coupon&.update(order: user_coupon, active: true)
    end
    redirect_to cart_path
  end
end

app/views/carts/_cart_book.html.haml
%tr
  %td
    .general-img-wrap-table
      = link_to order_item.book do
        = image_tag order_item.book.covers.first.variant(resize: "180x180").processed, class: "cart-img-shadow pull-left"
  %td
    = link_to order_item.book.title, order_item.book, class: 'title'
  %td
    %span.font-16.in-gold-500= price_euro(order_item.book.price)
  %td
    .input-group
      = form_for order_item, method: :put do |form|
        = link_to order_item_path(order_item, order_item: {quantity: -1}), class: 'input-link', method: :put do
          %i.fa.fa-minus.line-heaght-40
        = form.text_field :quantity, value: order_item.quantity, class: 'form-control quantity-input'
        = link_to order_item_path(order_item, order_item: {quantity: 1}), class: 'input-link', method: :put do
          %i.fa.a.fa-plus.line-heaght-40
  %td
    %span.font-16.in-gold-500= price_euro(order_item.book.price.to_d * order_item.quantity.to_d)
  %td
    = link_to order_item_path(order_item), class: 'button close delete-order-item', method: :delete do
      %span{'aria-hidden': "true"} &times;

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin=t('cart.cart')
  - unless @order_items.empty?
    .books
      .hidden-xs
        %table.table.table-hover
          %tr.no-hover
            %th.col-pic.pl-0
              %span.in-grey-600=t('cart.product')
            %th.col-title
            %th.col-price
              %span.in-grey-600=t('cart.price')
            %th.col-quantity
              %span.in-grey-600=t('cart.quantity')
            %th.col-total
              %span.in-grey-600=t('cart.subtotal')
            %th.col-close
          = render partial: 'cart_book', collection: @order_items, as: :order_item
      .general-order-wrap
        .row
          .col-sm-4
            = form_with url: cart_path, local: true, method: :patch  do |form|
              = form.label :code, t('cart.enter_coupon'), class: "input-label"
              = form.text_field :code, placeholder: t('cart.enter_coupon_code'), class: "form-control mb-30"
              %div
                = form.submit t('cart.apply_coupon'), class: "btn btn-primary mr-5 mb-15"
          .col-sm-8
            .res-mr-200.general-text-right
              %p.in-gold-500.font-18=t('cart.order_summary')
              %table.general-summary-table.general-summary-table-right.general-text-right
                %tr
                  %td
                    %p.font-16=t('cart.subtotal')
                  %td
                    %p.font-16= price_euro(@subtotal_price_sum)
                %tr
                  %td
                    %p.font-16=t('cart.coupon')
                  %td
                    %p.discount.font-16= price_euro(@discount)
                %tr
                  %td
                    %strong.font-18=t('cart.order_total')
                  %td
                    %strong.font-18= price_euro(@item_total_price)
      .text-center
        = link_to t('cart.checkout'), checkout_path(:login), class: "btn btn-default mb-20"
  - else
    %h2.general-title-margin.in-gold-500=t('cart.sorry')